### ISSUE TITLE
Remove `format=xxx` from query string

### ISSUE THREAD

**Issue by greystate** [sebastiandammark/umbraco7-xslt-helpers#3]
Having the **format** option in the query string seems to force download of the images, e.g. when you try to *Open image in new tab* from the context menu in the browser.

`GetCropUrl()` doesn't add the **format** option either

Label: **MediaHelper**

**Comment by sebastiandammark** [comment]
Fixed

**Comment by greystate** [comment]
Damn - I was just logging these to reference them from pull-requests later :-)

:+1:
